version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spotengine-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: u895854558_spotengine
      MYSQL_USER: u895854558_spotengine
      MYSQL_PASSWORD: Spotengine@484774
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
